// <auto-generated />
using System;
using BidWinAI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BidWinAI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622184238_AggiungiCampiIA")]
    partial class AggiungiCampiIA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BidWinAI.Models.Bando", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCaricamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Dimensione")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PercorsoFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtenteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtenteId");

                    b.ToTable("Bandi");
                });

            modelBuilder.Entity("BidWinAI.Models.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Utente");
                });

            modelBuilder.Entity("BidWinAI.Models.Bando", b =>
                {
                    b.HasOne("BidWinAI.Models.Utente", "Utente")
                        .WithMany("Bandi")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("BidWinAI.Models.Utente", b =>
                {
                    b.Navigation("Bandi");
                });
#pragma warning restore 612, 618
        }
    }
}
